colormap = {
    "Ibogaine"      : "C7",
    "Salvinorin A"  : "C6",
    "Ketamine"      : "C5",
    "5-MeO-DMT"     : "C0",
    "DMT"           : "C3",
    "LSD"           : "C2",
    "Psilocybin"    : "C1",
    "MDMA"          : "C4",
}

pharmacological_type = {
    "Ibogaine"      : "Psychedelic",
    "Salvinorin A"  : "Hallucinogen",
    "Ketamine"      : "Dissociative",
    "5-MeO-DMT"     : "Psychedelic",
    "DMT"           : "Psychedelic",
    "LSD"           : "Psychedelic",
    "Psilocybin"    : "Psychedelic",
    "MDMA"          : "Empathogen",
}

chemical_category = {
    "Ibogaine"      : "Tryptamine",
    "Salvinorin A"  : "Terpene",
    "Ketamine"      : "Arylcyclohexamine",
    "5-MeO-DMT"     : "Tryptamine",
    "DMT"           : "Tryptamine",
    "LSD"           : "Tryptamine",
    "Psilocybin"    : "Tryptamine",
    "MDMA"          : "Amphetamine",
}

alternative_names = [
    "DMT",
    "N,N-DMT",
    "Dmitry",
    "Glory",
    "Spirit Molecule",
    "5-MeO-DMT",
    "Toad",
    "Jaguar",
    "Soma",
    "God Molecule",
    "LSD",
    "LSD-25",
    "Lucy",
    "L",
    "Acid",
    "Cid",
    "Tabs",
    "Blotter",
    "Psilocybin",
    "Psilocin",
    "Mushrooms",
    "Magic mushrooms",
    "Shrooms",
    "MDMA",
    "Molly",
    "Mandy",
    "Emma",
    "MD",
    "Ecstasy",
    "E",
    "X",
    "XTC",
    "Ketamine",
    "K",
    "Kitty",
    "Special K",
    "Tranquilizer",
    "Vitamin K",
    "Purple",
    "Jet",
    "Salvianorin A",
    "Salvia",
    "Salvia Divinorum",
    "Sally",
    "Ibogaine",
    "Iboga",
    "Endabuse"
]